# Generated by Django 6.0.2 on 2026-02-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=4)),
                ('iata', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('subd', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('elevation', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('tz', models.CharField(max_length=200)),
                ('lid', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='TodoItems',
        ),
    ]
