# Generated by Django 6.0.2 on 2026-02-22 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_airports_rename_todoitem_todoitems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItems',
        ),
        migrations.AddField(
            model_name='airports',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_airports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airports',
            name='iata',
            field=models.CharField(max_length=3),
        ),
    ]
