# Generated by Django 6.0.2 on 2026-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_todoitems_airports_favorited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='icao',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
